on:
 push:
 workflow_dispatch:

jobs:
 cloudformationdeployent:
   runs-on: ubuntu:latest
   steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::851725476509:role/github-action-role-vpc
        role-session-name: MySessionName
