on:
 push:
 workflow_dispatch:

jobs:
 cloudformationdeployent:
   runs-on: ubuntu-latest
   steps:
   - name: configure aws credentials
     uses: aws-actions/configure-aws-credentials@v3
     with:
          role-to-assume: arn:aws:iam::851725476509:role/github-action-role-vpc
          role-session-name: samplerolesession
